FROM golang:1.18-alpine

RUN mkdir /app

RUN addgroup -S firdagroup
RUN adduser -S -D -h /app firdauser firdagroup
RUN chown -R firdauser:firdagroup /app
USER firdauser

COPY main.go /app


EXPOSE 8080
CMD go run /app/main.go